// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4tWdXU77Psb-GdV4biSq4Kq_EKYLKzPo',
    appId: '1:769341373683:web:a5156dee4093bbe0d8cb86',
    messagingSenderId: '769341373683',
    projectId: 'a3usabilidade',
    authDomain: 'a3usabilidade.firebaseapp.com',
    storageBucket: 'a3usabilidade.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvrCY_dl-u9cAXzqJMz0N25LzCfSaRGY',
    appId: '1:769341373683:android:ce7795802877cf9bd8cb86',
    messagingSenderId: '769341373683',
    projectId: 'a3usabilidade',
    storageBucket: 'a3usabilidade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUDFoxwVizu-XSGKkgKe_PjHKIvkx_Yg',
    appId: '1:769341373683:ios:f209856f1c3c4d5ed8cb86',
    messagingSenderId: '769341373683',
    projectId: 'a3usabilidade',
    storageBucket: 'a3usabilidade.appspot.com',
    iosClientId: '769341373683-vp0akf4p0r857fcm95moojaqt6elmqnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.olimpiadas',
  );
}
